// Command generate-reference verifies Go declaration comments and generates a
// complete source-linked symbol reference for the repository.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const outputPath = "docs/generated/go-symbols.md"

// declaration is one source-linked documented symbol row.
type declaration struct {
	Kind    string
	Symbol  string
	Source  string
	Line    int
	Summary string
}

// main parses flags, validates declarations, and writes or checks the reference.
func main() {
	write := flag.Bool("write", false, "write the generated reference")
	flag.Parse()

	declarations, undocumented, err := scanDeclarations()
	if err != nil {
		fatal(err)
	}
	if len(undocumented) > 0 {
		fatal(fmt.Errorf("undocumented Go declarations:\n%s", strings.Join(undocumented, "\n")))
	}

	content := renderReference(declarations)
	if *write {
		if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(outputPath, content, 0o644); err != nil {
			fatal(err)
		}
		return
	}

	current, err := os.ReadFile(outputPath)
	if err != nil {
		fatal(fmt.Errorf("read generated reference: %w", err))
	}
	if !bytes.Equal(current, content) {
		fatal(fmt.Errorf("%s is stale; run go run ./scripts/generate-reference.go -write", outputPath))
	}
}

// scanDeclarations collects documented types, functions, and methods.
func scanDeclarations() ([]declaration, []string, error) {
	fset := token.NewFileSet()
	var declarations []declaration
	var undocumented []string
	for _, root := range []string{"cmd", "internal", "scripts"} {
		err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() || filepath.Ext(path) != ".go" {
				return nil
			}
			file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
			if err != nil {
				return err
			}
			for _, node := range file.Decls {
				switch item := node.(type) {
				case *ast.FuncDecl:
					symbol := item.Name.Name
					kind := "function"
					if item.Recv != nil {
						kind = "method"
						symbol = receiverName(fset, item.Recv) + "." + symbol
					}
					appendDeclaration(fset, path, kind, symbol, item.Pos(), item.Doc, &declarations, &undocumented)
				case *ast.GenDecl:
					if item.Tok != token.TYPE {
						continue
					}
					for _, spec := range item.Specs {
						typeSpec := spec.(*ast.TypeSpec)
						doc := typeSpec.Doc
						if doc == nil {
							doc = item.Doc
						}
						appendDeclaration(fset, path, "type", typeSpec.Name.Name, typeSpec.Pos(), doc, &declarations, &undocumented)
					}
				}
			}
			return nil
		})
		if err != nil {
			return nil, nil, err
		}
	}
	sort.Slice(declarations, func(i, j int) bool {
		if declarations[i].Source == declarations[j].Source {
			return declarations[i].Line < declarations[j].Line
		}
		return declarations[i].Source < declarations[j].Source
	})
	return declarations, undocumented, nil
}

// appendDeclaration validates one comment and appends its normalized summary.
func appendDeclaration(fset *token.FileSet, path, kind, symbol string, pos token.Pos, doc *ast.CommentGroup, declarations *[]declaration, undocumented *[]string) {
	position := fset.Position(pos)
	label := fmt.Sprintf("%s:%d %s", path, position.Line, symbol)
	if doc == nil || strings.TrimSpace(doc.Text()) == "" {
		*undocumented = append(*undocumented, label)
		return
	}
	*declarations = append(*declarations, declaration{
		Kind: kind, Symbol: symbol, Source: path, Line: position.Line,
		Summary: firstSentence(doc.Text()),
	})
}

// receiverName renders the method receiver without its variable name.
func receiverName(fset *token.FileSet, fields *ast.FieldList) string {
	var buffer bytes.Buffer
	if len(fields.List) == 0 {
		return "unknown"
	}
	if err := printer.Fprint(&buffer, fset, fields.List[0].Type); err != nil {
		return "unknown"
	}
	return buffer.String()
}

// firstSentence flattens a Go comment to one Markdown-table-safe summary.
func firstSentence(value string) string {
	value = strings.Join(strings.Fields(value), " ")
	if index := strings.Index(value, ". "); index >= 0 {
		value = value[:index+1]
	}
	return strings.ReplaceAll(value, "|", "\\|")
}

// renderReference creates a deterministic Markdown table for every declaration.
func renderReference(declarations []declaration) []byte {
	var output strings.Builder
	output.WriteString("# Generated Go Symbol Reference\n\n")
	output.WriteString("Generated by `go run ./scripts/generate-reference.go -write`. ")
	output.WriteString("Do not edit this file by hand. Every type, function, and method under ")
	output.WriteString("`cmd/`, `internal/`, and `scripts/` must have a source comment.\n\n")
	fmt.Fprintf(&output, "Declarations: **%d**\n\n", len(declarations))
	output.WriteString("| Kind | Symbol | Source | Contract summary |\n")
	output.WriteString("| --- | --- | --- | --- |\n")
	for _, item := range declarations {
		fmt.Fprintf(&output, "| %s | `%s` | `%s:%d` | %s |\n", item.Kind, item.Symbol, item.Source, item.Line, item.Summary)
	}
	return []byte(output.String())
}

// fatal prints a generator error and terminates with a non-zero status.
func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate-reference:", err)
	os.Exit(1)
}
